version: '3'
services:
  nodejs-express:
    build: ./nodejs/express/
    ports:
      - 8080:8080
  nodejs-hapi:
    build: ./nodejs/hapi/
    ports:
      - 8081:8081
  nodejs-nestjs:
    build: ./nodejs/nestjs/
    ports:
      - 8082:3000
  nodejs-nextjs:
    build: ./nodejs/nextjs/
    ports:
      - 8083:3000
  php-symfony:
    build: ./php/symfony/
    ports:
      - 8000:8000
  python-flask:
    build: ./python/flask/
    ports:
      - 5000:5000